<a href="https://colab.research.google.com/github/sushant758/MATHS-FOR-ML-/blob/main/day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('student_scores.csv')

In [ ]:
df.head()

      name  math  science  english  social
0    Alice    78       85       90      70
1      Bob    92       88       80      75
2  Charlie    85       95       85      78
3    David    70       72       75      65
4      Eva    88       91       82      79

In [ ]:
df.shape

(10, 5)

In [5]:
df.columns

Index(['name', 'math', 'science', 'english', 'social'], dtype='object')

In [6]:
numeric_df = df.select_dtypes(include=np.number)

In [7]:
numeric_df.head()

   math  science  english  social
0    78       85       90      70
1    92       88       80      75
2    85       95       85      78
3    70       72       75      65
4    88       91       82      79

In [8]:
print("\nNumeric Data:")
print(numeric_df)

Numeric Data:
   math  science  english  social
0    78       85       90      70
1    92       88       80      75
2    85       95       85      78
3    70       72       75      65
4    88       91       82      79
5    60       65       68      60
6    95       98       92      85
7    82       77       88      82
8    76       84       80      74
9    89       92       90      81

In [9]:
# Convert to NumPy array
matrix = numeric_df.to_numpy()

In [10]:
print("\nNumPy Matrix:")
print(matrix)

NumPy Matrix:
[[78 85 90 70]
 [92 88 80 75]
 [85 95 85 78]
 [70 72 75 65]
 [88 91 82 79]
 [60 65 68 60]
 [95 98 92 85]
 [82 77 88 82]
 [76 84 80 74]
 [89 92 90 81]]

In [11]:
matrix.shape

(10, 4)

In [12]:
# Manual Transpose (without using .T)
rows, cols = matrix.shape

manual_transpose = []

for col in range(cols):
    new_row = []

    for row in range(rows):
        new_row.append(matrix[row][col])

    manual_transpose.append(new_row)

manual_transpose = np.array(manual_transpose)

print("\nManual Transpose:")
print(manual_transpose)

Manual Transpose:
[[78 92 85 70 88 60 95 82 76 89]
 [85 88 95 72 91 65 98 77 84 92]
 [90 80 85 75 82 68 92 88 80 90]
 [70 75 78 65 79 60 85 82 74 81]]

In [13]:
# NumPy Transpose for verification
numpy_transpose = matrix.T

In [14]:
print(numpy_transpose)

[[78 92 85 70 88 60 95 82 76 89]
 [85 88 95 72 91 65 98 77 84 92]
 [90 80 85 75 82 68 92 88 80 90]
 [70 75 78 65 79 60 85 82 74 81]]

In [15]:
# Both are same